// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Robert Vokac and contributors
#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include "ChunkCoord.hpp"
#include "ModelPlacement.hpp"
#include "ZoneType.hpp"
#include "RegionType.hpp"
#include "WorldMap.hpp"

namespace MeshWorld {

struct GeneratorConstraints {
    int  max_objects{80};
    int  max_triangles{12000};
    bool no_characters{true};
    bool no_text{true};
    bool no_brands{true};
};

// Macro-scale context handed down from the planetary map layer (MAP10, M158).
// Plain fields rather than a Map::MapTilePayload reference, so chunk generators
// stay decoupled from the Map:: subsystem headers. `available` is false until
// ChunkPipeline populates it from MapPipeline (M159); generators must fall back
// to the flat WorldMap-derived `zone`/`region`/`exits` above when it is false.
struct MapContext {
    bool          available{false};
    std::uint8_t  biome_ordinal{0};    // Map::BiomeGrid value; maps to ZoneType at hand-off
    float         elevation_m{0.0f};   // Map::FieldGrid elevation sample at chunk center
    bool          is_city{false};      // from map settlement features (MAP9, not yet generated)
    bool          has_road_crossing{false};  // from map road network (MAP9, not yet generated)
    // Map::ZoneCandidate ordinal (M156/M157); maps to RegionType at hand-off.
    // Default 0 == Map::ZoneCandidate::none, the correct sentinel for both
    // "not populated" and "this cell wasn't part of a zoned block" — the
    // grid a value came from (MapTilePayload::zone_candidates) uses the
    // same convention (see city.lua's own header note).
    std::uint8_t  zone_candidate_ordinal{0};

    // M158 — nearest river (from Map::FeatureType::River features, MAP8's
    // Hydrology/FeatureNaming; not yet generated by anything: only the C++
    // PlanetGenerator/ChildGenerator path wires Hydrology in, and no
    // ChunkPipeline code samples it yet — that's a later task). Empty
    // name / negative distance means "not computed" or "no river within
    // range" — distinct from a genuine river passing through the chunk
    // (distance 0).
    std::string   nearest_river_name;
    float         nearest_river_distance_m{-1.0f};

    // M158 — nearest named place (Map::PlaceLabel — settlements, countries,
    // etc.; MAP9's Settlements::appendLabels()/Countries::name(), not yet
    // wired into any real generator, see NEXT.md §2). Mirrors PlaceLabel's
    // own {name, kind} shape rather than exposing Map::PlaceLabel directly,
    // keeping MapContext decoupled from Map:: headers — same reasoning
    // biome_ordinal/zone_candidate_ordinal already use (raw values, not
    // typed Map:: enums/structs).
    std::string   nearest_place_name;
    std::string   nearest_place_kind;  // "city"/"country"/"region"/... (PlaceLabel::kind)
};

// R128 (city showcase completion) -- resolved, per-chunk counterpart of
// WorldConfig::LandmarkPlacement (that struct filtered down to just the
// ONE entry, if any, matching THIS chunk's own coord). A plain field
// rather than a WorldConfig reference, mirroring MapContext's own
// "plain fields, not a subsystem reference" decoupling rule. Empty
// `definition_id` (the default) is the sentinel for "no landmark
// configured here" -- the overwhelmingly common case.
struct LandmarkInstance {
    std::string definition_id;
    float       x{0.0f};
    float       z{0.0f};
    float       rotation_y{0.0f};
};

struct ChunkContext {
    ChunkCoord           coord;
    uint64_t             seed{0};
    // M332 (MAP21) -- the raw per-world seed `seed` above was itself
    // derived from (chunk_seed(world_seed, coord)), so two neighboring
    // chunks' own `seed` values are unrelated hash outputs, useless for
    // computing something two INDEPENDENT generate() calls must agree on
    // (e.g. CaveLayout's cross-chunk tunnel-opening symmetry -- chunk A's
    // own opening toward B must equal chunk B's own opening toward A).
    // This exposes the one shared value both sides genuinely need.
    // Defaults to 0 (matches every pre-M332 test's implicit assumption of
    // "whatever, not used") -- ChunkPipeline populates the real value.
    uint64_t             world_seed{0};
    ZoneType             zone{ZoneType::empty};
    // R129 (zone-metadata bug fix, NEXT.md §4) -- the flat WorldMap/
    // WorldConfig-derived zone (`ci.zone`), captured BEFORE the M157
    // map-layer override below can replace `zone` with the planet's own
    // sampled biome. `zone` itself is intentionally left untouched by this
    // fix -- it still drives real generator-routing decisions
    // (get_generator(ctx.zone, ctx.region) in ChunkPipeline::get(), and
    // ChunkPipelineMapContextTests.cpp's own ZoneOverriddenByMapBiome-
    // WhenAvailable test locks that override in as intended behavior for
    // genuinely map-integrated worlds). `authored_zone` exists purely so
    // GenerationMetadata can report the zone this world's own flat config
    // actually authored, instead of an unrelated planet's biome at
    // whatever coordinates a freshly auto-created hand-off world happens
    // to occupy (the common case for MeshWorldExport, which always
    // attaches a MapPipeline -- see export_chunks.cpp). Always equals
    // `zone` when no MapPipeline is attached or no override applies.
    ZoneType             authored_zone{ZoneType::empty};
    RegionType           region{RegionType::empty};
    std::string          style{"central_europe_small_city"};
    float                chunk_size_m{64.0f};
    // Level of detail, 0 (coarse silhouette) .. 4 (high-detail near-camera),
    // per docs/procedural-model-generator-roadmap.md's LOD convention.
    // Long documented in docs/lua-generators.md as ctx.lod without any C++
    // field ever backing it -- this is that field finally existing. Default
    // 2 ("normal gameplay object"); no caller sets a different value yet
    // (a real distance-based LOD picker is future work, not this field).
    int                  lod{2};
    EdgeExits            exits;
    GeneratorConstraints constraints;
    MapContext           map_context;
    // R128 -- populated by ChunkPipeline::build_context() from
    // WorldConfig::landmarks; see LandmarkInstance's own doc comment.
    LandmarkInstance     landmark;
};

// M297 (MAP17, 2026-07-10) -- CONTRACT: every ChunkGenerator::generate()
// override must read ctx.map_context in some way when
// ctx.map_context.available is true. This is a hard requirement per
// explicit user instruction ("all chunk generators should use the new map
// system, no exceptions carved out") -- not just "where geometrically
// meaningful". As of this date all 20 existing generators comply (the last
// 16 wired up this same session, following ForestGenerator/OceanGenerator/
// MeadowGenerator/MountainGenerator's original M160 template); see
// tests/ChunkGeneratorMapContextAuditTests.cpp for the automated check.
// A generator's own map_context read doesn't need to change generate()'s
// core geometry -- appending purely-additive extra content after every
// pre-existing draw (so the base RNG sequence is identical with or without
// a map layer attached) is a fully compliant, low-risk way to satisfy this,
// and is what most of the 20 generators do today. This is a documentation/
// convention contract, not a compile-time-enforced one (C++ has no clean
// way to statically verify a function body reads a specific field) -- the
// audit test is what actually enforces it.
class ChunkGenerator {
public:
    virtual ~ChunkGenerator() = default;
    virtual std::string generate(const ChunkContext& ctx) = 0;

    // M168 (MAP11) -- ModelPlacements for this chunk's streamable objects
    // (trees, etc.), IN ADDITION TO generate()'s inline MC3 instances, not
    // replacing them -- migrating rendering to stream placements instead of
    // inline MC3 is a later task (M175's WorldRenderer integration). Default
    // is empty: most generators don't need to override this yet, matching
    // this codebase's established "N-of-~20 generator slice" precedent
    // (e.g. M160's map_context rollout to 2 generators first).
    virtual std::vector<ModelPlacement> placements(const ChunkContext& ctx) const {
        (void)ctx;
        return {};
    }
};

// Fallback chain: exact (zone,region) → any-zone region → zone open → EmptyGenerator.
ChunkGenerator* get_generator(ZoneType z, RegionType r);

} // namespace MeshWorld
