-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 Robert Vokac and contributors
--
-- M154 (MAP10) — Lua child-tile generator for level 15 ("Neighborhood"
-- scale detail within a parent tile, ~688 m per map.md's level table).
-- Registered as "lua.map.child.level15.default" so MapPipeline's
-- level-aware Lua lookup (M115) only tries this for level-15 tiles.
--
-- Mirrors city.lua's (M153) generic child-refinement technique (bilinear-
-- from-parent elevation + fade-to-zero fBm detail; temperature and
-- moisture recomputed from world position) for the same reasons documented
-- there (elevation stays continuous with the parent, M112 sibling
-- coherence). The immediate parent here is a level-14 ("Town / borough")
-- tile, generated by the generic C++ subdivision (no dedicated Lua script
-- at that level yet) -- same shape/fields as any other parent regardless.
--
-- SCOPE: plan.md's M154 wording is specifically "individual named
-- streets" -- narrower than M153's "street grid, zoning, parks, water".
-- Zoning (RegionType candidates) is its own later checkbox, M156. Street
-- terrain-alignment (M155) IS applied here too, via city.lua's own
-- align_grid_line() technique duplicated below (see city.lua's header for
-- the full reasoning: a cheap greedy contour-following walk, not a full
-- Dijkstra). "Blocks between streets" (M155's other clause) is NOT
-- modeled at this level either -- see city.lua's header note; map.md's
-- level table puts "block cluster" at level 16, one below this one. So
-- THIS script adds ONLY a (now terrain-aligned) finer street grid -- no
-- markUrbanCells() zoning override, no addPark()/addLake() calls. Read
-- city.lua's header first if you haven't;
-- the same "ctx.parent only exposes elevation/temperature/moisture/
-- culture/variation, never a parent's placed features" limitation applies
-- here (see LuaRuntime.cpp's make_parent_table()) -- this script has no
-- way to see city.lua's (level 12) actual street/block positions 3 levels
-- up, so like every level so far it makes its own independent decision at
-- its own resolution rather than reading an ancestor's placed features.
--
-- Per map.md's level table, level 15 is 8x finer than level 12 (~688 m vs
-- ~5.5 km tiles) and is specifically about "individual streets, named" --
-- NOT a re-run of city.lua's coarse arterial grid at higher resolution.
-- City.lua's own STREET_SPACING_CELLS=8 over a 64-cell/5.5km tile already
-- lands almost exactly on this level's tile size (~688 m), i.e. city.lua's
-- grid IS the arterial spacing this level's tiles sit between. So this
-- script uses a noticeably tighter spacing (STREET_SPACING_CELLS=4, over a
-- ~10.75 m/cell tile -> ~43 m block faces) to add genuinely new, finer
-- local streets, still land-gated the same way city.lua gates its own grid
-- (no streets at all over a tile with no buildable land).
--
-- KNOWN LIMITATIONS (same as the other child scripts):
-- * ctx does not expose WorldConfig (sea level, equator/pole temperature)
--   to Lua generators yet -- hardcodes the same defaults the other
--   scripts do.
-- * MapBuilder::setBiomeField's M108 constraint overwrites this tile's own
--   boundary rows/columns on the 2 sides that touch the parent's
--   boundary; the OTHER 2 sides (shared with a sibling) rely on this
--   script's own bilinear math matching what the sibling computes, same
--   as the others.

local M = {}
M.id       = "lua.map.child.level15.default"
M.version  = "0.1.0"
M.category = "map"

local GRID_SIZE             = 64
local SEA_LEVEL_M           = 0.0    -- WorldConfig default; see header note
local EQUATOR_TEMP_C        = 30.0
local POLE_TEMP_C           = -20.0
local MOUNTAIN_ELEV_M       = 2500.0 -- above sea level; mirrors BiomeClassifier
local DETAIL_OFFSET         = 2000.0 -- decorrelates detail noise (ctx.noise has one fixed seed)
local MOISTURE_OFFSET       = 6000.0 -- decorrelates moisture noise from detail noise
local STREET_SPACING_CELLS  = 4      -- finer than city.lua's 8 -- see header note
local SAMPLE_STEP_CELLS     = 4      -- M155: waypoint spacing along a bent street line
local MAX_DRIFT_CELLS       = 1      -- M155: max lateral bend from the straight index (tighter than city.lua's 2 -- this grid's own spacing is tighter too)
-- M162 fix (§5 #18): tile bounds are half-open [min,max) (MapValidator rejects a point at
-- exactly max_x/max_z), but MapBuilder::deriveEdgeCrossings() only matches within 0.01 m
-- of the true edge -- this must be strictly less than max but within that tolerance.
local EDGE_SNAP_EPS_M       = 0.001
-- M354 (MAP24, found 2026-07-10): must match ZoneType::city's ordinal
-- (include/ZoneType.hpp) -- city is that enum's first value, ordinal 0.
local CITY_ORDINAL          = 0

-- Bilinear interpolation of a {w=,h=,data={...}} field-grid table at
-- fractional position (fx, fy). Mirrors ChildGenerator.cpp's private helper
-- of the same name/shape (also used by continent.lua/region.lua/
-- country.lua/metro.lua/city.lua).
local function bilinear(grid, fx, fy)
    fx = math.max(0.0, math.min(grid.w - 1, fx))
    fy = math.max(0.0, math.min(grid.h - 1, fy))
    local x0 = math.floor(fx)
    local y0 = math.floor(fy)
    local x1 = math.min(x0 + 1, grid.w - 1)
    local y1 = math.min(y0 + 1, grid.h - 1)
    local tx = fx - x0
    local ty = fy - y0
    local function at(gx, gy) return grid.data[gy * grid.w + gx + 1] end
    local v00, v10 = at(x0, y0), at(x1, y0)
    local v01, v11 = at(x0, y1), at(x1, y1)
    local a = v00 + (v10 - v00) * tx
    local b = v01 + (v11 - v01) * tx
    return a + (b - a) * ty
end

-- M155: bends a straight axis-aligned grid line to loosely follow terrain.
-- Exact duplicate of city.lua's own align_grid_line() -- see its header
-- note for the full reasoning (greedy contour-following walk, not a full
-- Dijkstra); duplicated rather than shared since these Lua generator
-- scripts have no shared-module mechanism, same as bilinear() above.
local function align_grid_line(elevation, W, H, vertical, fixed_index, child_x0, child_y0, child_size_m)
    local along_len = vertical and H or W
    local cross_len = vertical and W or H
    local function elev_at(along, cross)
        local gx = vertical and cross or along
        local gy = vertical and along or cross
        return elevation[gy * W + gx + 1]
    end
    -- along_boundary, when non-nil, overrides the along-axis world coordinate with the
    -- tile's true edge (child_{x,y}0 or +child_size_m) instead of the cell-center formula,
    -- so the first/last sampled point lands exactly on the boundary that
    -- MapBuilder::deriveEdgeCrossings() checks against (bent cross-axis untouched).
    local function world_point(along, cross, along_boundary)
        local gx = vertical and cross or along
        local gy = vertical and along or cross
        local px = child_x0 + (gx + 0.5) * child_size_m / W
        local pz = child_y0 + (gy + 0.5) * child_size_m / H
        if along_boundary ~= nil then
            if vertical then pz = along_boundary else px = along_boundary end
        end
        return {px, pz}
    end
    local along_min = vertical and child_y0 or child_x0
    local along_max = along_min + child_size_m - EDGE_SNAP_EPS_M

    local lo, hi = math.max(0, fixed_index - MAX_DRIFT_CELLS), math.min(cross_len - 1, fixed_index + MAX_DRIFT_CELLS)
    local points = {}
    local prev_cross = fixed_index
    local prev_elev  = elev_at(0, fixed_index)
    local last_along = 0
    for along = 0, along_len - 1, SAMPLE_STEP_CELLS do
        local best_cross, best_diff = prev_cross, math.huge
        for d = -1, 1 do
            local cand = prev_cross + d
            if cand >= lo and cand <= hi then
                local diff = math.abs(elev_at(along, cand) - prev_elev)
                if diff < best_diff then
                    best_diff, best_cross = diff, cand
                end
            end
        end
        prev_cross = best_cross
        prev_elev  = elev_at(along, best_cross)
        last_along = along
        local boundary = nil
        if along == 0 then boundary = along_min end
        if along == along_len - 1 then boundary = along_max end
        points[#points + 1] = world_point(along, best_cross, boundary)
    end
    if last_along ~= along_len - 1 then
        points[#points + 1] = world_point(along_len - 1, prev_cross, along_max)
    end
    return points
end

function M.generate(ctx, map)
    local parent = ctx.parent
    if not parent then return end  -- level 15 always has a parent; defensive only

    local W, H = GRID_SIZE, GRID_SIZE
    local cx = ctx.tile_x % 2
    local cy = ctx.tile_y % 2

    local planet_size_m = ctx.tile_size_m * (2 ^ ctx.level)
    local child_size_m  = ctx.tile_size_m
    local child_x0      = ctx.tile_x * child_size_m
    local child_y0      = ctx.tile_y * child_size_m

    local terrain_scale = math.max(child_size_m / 4.0, 1.0)
    local detail_amp    = math.min(child_size_m / 100.0, 500.0)

    local elevation, temperature, moisture = {}, {}, {}
    local is_buildable  = {}  -- land, not too high -- gates whether streets are placed at all
    local any_buildable = false
    -- M354 (MAP24, found 2026-07-10): nearest-neighbor sample of the
    -- parent's own classified biome per cell -- see the CITY_ORDINAL/
    -- markUrbanCells() use below the main loop for why.
    local parent_city  = {}
    local any_parent_city = false
    local parent_biome_w, parent_biome_h = parent.biome.w, parent.biome.h

    for gy = 0, H - 1 do
        for gx = 0, W - 1 do
            local pgx = cx * 32.0 + gx * (32.0 / (W - 1))
            local pgy = cy * 32.0 + gy * (32.0 / (H - 1))
            local base_elev = bilinear(parent.elevation, pgx, pgy)

            local pbx = math.max(0, math.min(parent_biome_w - 1, math.floor(pgx + 0.5)))
            local pby = math.max(0, math.min(parent_biome_h - 1, math.floor(pgy + 0.5)))
            local is_city = parent.biome.data[pby * parent_biome_w + pbx + 1] == CITY_ORDINAL
            -- markUrbanCells() (below, after setBiomeField()) round-trips
            -- through table_to_float_vec()/obj_float(), which only handles
            -- Lua numbers -- a raw boolean silently becomes 0 (obj_float()'s
            -- default), not an error, so this MUST be 1/0, not true/false,
            -- same idiom city.lua's own urban_mask already uses.
            parent_city[gy * W + gx + 1] = is_city and 1 or 0
            if is_city then any_parent_city = true end

            local fx_fade = math.sin(math.pi * gx / (W - 1))
            local fy_fade = math.sin(math.pi * gy / (H - 1))
            local fade    = fx_fade * fx_fade * fy_fade * fy_fade

            local wx = child_x0 + (gx + 0.5) * child_size_m / W
            local wy = child_y0 + (gy + 0.5) * child_size_m / H

            local detail_fbm = ctx.noise(wx / terrain_scale + DETAIL_OFFSET, wy / terrain_scale)
            local elev = base_elev + fade * (detail_fbm - 0.5) * detail_amp

            local lat_factor = math.abs(wy / planet_size_m - 0.5) * 2.0
            local base_temp  = EQUATOR_TEMP_C + (POLE_TEMP_C - EQUATOR_TEMP_C) * lat_factor
            local elev_above = math.max(elev - SEA_LEVEL_M, 0.0)
            local temp       = base_temp - 6.5 * elev_above / 1000.0

            local moisture_fbm = ctx.noise(wx / terrain_scale + MOISTURE_OFFSET, wy / terrain_scale)
            local moist = math.max(0.0, math.min(1.0, moisture_fbm))

            local idx = gy * W + gx + 1
            elevation[idx]   = elev
            temperature[idx] = temp
            moisture[idx]    = moist

            local elev_above_sea = elev - SEA_LEVEL_M
            local buildable = elev_above_sea > 0.0 and elev_above_sea < MOUNTAIN_ELEV_M
            is_buildable[idx] = buildable
            if buildable then any_buildable = true end
        end
    end

    -- setBiomeField() default-derives all 4 edges from this tile's own FINAL
    -- elevation (M115, MapBuilder.cpp) — see continent.lua's header note for
    -- why this script (like the others) must not call setEdge() itself.
    -- No NEW zoning here — zoning (Map::ZoneCandidate) is M156's job, not
    -- M154's. markUrbanCells() below is not new zoning, it's re-applying an
    -- override this tile's own ancestor chain already made (M354).
    map:setBiomeField(W, H, elevation, temperature, moisture)

    -- MAP19, M315/M317: coastal beach + swamp-flatness refinement, BEFORE
    -- the M354 markUrbanCells() re-application below so the inherited city
    -- override always wins over natural refinement (same precedence note
    -- that call already documents). No river/mountain trace at this scale
    -- (~688 m tile) -- see city.lua's own M317 note for why: any real
    -- influence should already be visible in the inherited parent elevation.
    map:applyCoastalBeach()
    map:applySwampFlatnessCheck()

    -- M259/M274/M275 (2026-07-11): canyon carving + coastal relief
    -- refinement (tidal_flat/sea_cliff), same "before the M354
    -- markUrbanCells() re-application below" precedence as the two calls
    -- above.
    map:applyCanyonCarving()
    map:applyCoastalReliefRefinement()

    -- M354 (MAP24, found 2026-07-10): BiomeClassifier (just run inside
    -- setBiomeField() above) has no "city" output, so without this, a
    -- "City" zone set by an ancestor (ultimately city.lua, level 12, or a
    -- future MAP18 script) silently evaporates at this level -- this tile's
    -- own elevation/temperature/moisture recompute (above) has no way to
    -- know about it on its own. Re-applies markUrbanCells() wherever the
    -- parent's own classified biome was already ZoneType::city.
    if any_parent_city then
        map:markUrbanCells(parent_city)
    end

    if any_buildable then
        -- Individual local streets: a finer grid than city.lua's own
        -- arterial one (see header note on spacing), each line bent to
        -- loosely follow terrain (M155) via align_grid_line().
        for gx = 0, W - 1, STREET_SPACING_CELLS do
            local street_name = names.street(parent.culture, ctx.variation + 200 + gx)
            local path = align_grid_line(elevation, W, H, true, gx, child_x0, child_y0, child_size_m)
            map:addStreet(street_name, path)
        end
        for gy = 0, H - 1, STREET_SPACING_CELLS do
            local street_name = names.street(parent.culture, ctx.variation + 300 + gy)
            local path = align_grid_line(elevation, W, H, false, gy, child_x0, child_y0, child_size_m)
            map:addStreet(street_name, path)
        end
    end

    map:setMetadata(M.id, parent.culture)
end

return M
