#pragma once

#include <cstddef>
#include <string>

namespace IronGang
{
    // plan_36 IG-36-002/006/009: hard bounds for every small JSON data file the game reads --
    // missions, configuration, vehicle tuning, dialogue, cutscenes.
    //
    // These files are content: hand-authored today, but the project's own scope decisions treat
    // downloaded and generated assets as untrusted (IG-36-001), and "we wrote it ourselves" stops
    // being true the first time one is generated by a tool or shipped in a package. A parser is
    // the wrong place to discover that a file is 900 MB or nested ten thousand deep.
    //
    // 1 MiB is roughly a hundred times the largest file the game currently ships, and a depth of
    // 32 is far past anything a hand-authored mission needs -- both are meant to be unreachable by
    // real content and fatal to a hostile file.
    inline constexpr std::size_t kMaxJsonDataFileBytes = 1024U * 1024U;
    inline constexpr int kMaxJsonDataFileDepth = 32;

    // Reads @p path into @p out after checking it, in this order:
    //
    //   * the file's size is read from the filesystem, so an oversized file is refused **without
    //     being loaded into memory**;
    //   * the bytes are validated as UTF-8 (rejecting overlong forms, surrogates, and anything
    //     above U+10FFFF), so a malformed identifier cannot reach a string comparison;
    //   * nesting depth is counted over the raw text, so a document deep enough to exhaust the
    //     stack is refused rather than handed to a recursive-descent parser.
    //
    // Returns false with an actionable errorMessage on any of those, or on a missing/unreadable
    // file. This header deliberately exposes no JSON types: sharp-runtime's Text.Json is a private
    // dependency of iron_gang_core, and a bounded read is useful to anything that reads text.
    [[nodiscard]] bool ReadBoundedJsonText(const std::string& path, std::string& out, std::string& errorMessage);

    // The two checks on their own, for callers that already have the text -- and for tests.
    [[nodiscard]] bool IsValidUtf8(const std::string& text);
    // Deepest nesting of {} and [] in @p text, ignoring braces inside strings. Returns -1 if the
    // brackets are unbalanced or a string is unterminated, which the parser would reject anyway --
    // reporting it here keeps the failure on this side of the parser.
    [[nodiscard]] int MeasureJsonNestingDepth(const std::string& text);
}
